version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./backend/.env  # Load environment variables from .env file
    ports:
      - "5050:80"
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  # backend:
  #   build:
  #     context: ./backend  # Replace with the path to your backend directory
  #   container_name: backend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - mynetwork

  frontend:
    build:
      context: ./frontend  # Replace with the path to your frontend directory
    container_name: frontend
    ports:
      - "9090:9090"
    #depends_on:
    #  - backend  # You can add other dependencies as needed
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  pg_data :
