version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    container_name: nginx
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: postgres

  backend:
   build:
     context: ./backend
     dockerfile: Dockerfile
   ports:
     - "3000:3000"
   depends_on:
     - postgres