version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - transcendance_network
    #restart : always

  pgadmin:
    image: fenglc/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env
 
    volumes:
    - data:/var/lib/pgadmin
    - ./pgadmin/config:/pgadmin4
    restart : always
    networks:
      - transcendance_network

  backend:
    container_name: backend_nest
    restart: unless-stopped
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    networks:
      - transcendance_network
    volumes:
      - ./backend:/app
    depends_on:
      - postgres


networks:
  transcendance_network:
    driver: bridge

volumes:
  data: